name: CI/CD

on:
  push:
  pull_request:
  schedule:
  - cron:  '1 0 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        repository: coreweave/fah-gpu
        dockerfile: Dockerfile
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List built image
      run: docker images
    - name: Build GPU only Docker image
      uses: docker/build-push-action@v1
      with:
        repository: coreweave/fah-gpu
        dockerfile: Dockerfile.gpuonly
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List built GPU image
      run: docker images
